# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 602aac853dd601e8b4b2a4795eaa04afc44714d45eea718b79ec224372ab4d0b60dc3b73b3dcece7bf7238638b7077ea8bdd914fe96c960bf877bfedf33bcbe9

test:
  secret_key_base: f8497bf9596650bed3d9663a3e434fa884a510934fa5a986d8d3398a12b908a1f2e91dd2314f0cc46aa6c23de24a7b426c1c774410e27a6f12d709b92fbe4437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
